package:
  name: pyaerocom
  version: "0.7.1"

source:
  git_rev: v0.7.1
  git_url: https://github.com/metno/pyaerocom

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - iris >=2.1.0
    - xarray >=0.10.8
    - matplotlib >=3.0.1
    - cartopy >=0.16.0
    - pandas >=0.23.0
    - seaborn >=0.8.1
    - scipy>=1.1.0
    - numpy
    - netcdf4
    - pytest

test:
  imports:
    - pyaerocom

about:
  home: https://github.com/metno/pyaerocom
  license: GPLv3
  license_file: LICENSE
